### ISSUE TITLE
Attaching to server console during installation crashes Wilfred

### ISSUE THREAD

**Issue by VilhelmPrytz** [wilfred-dev/wilfred#46]
### Environment

* Installation type: snap & pip
* Python version:  3.6.9 (affects all supported versions)
* Wilfred version: since `v0.5.0`

### Steps to Reproduce

Create a server with `wilfred create --detach` and attach to console `wilfred console <name>` when the server is still installing.

### Expected Behavior

The log to be streamed with input disabled.

### Observed Behavior

The following exception is raised.

```bash
Viewing server console of test (id yyl8lsr5) - input disabled, installing
Traceback (most recent call last):
  File "run.py", line 16, in <module>
    main()
  File "/home/vilhelm/src/github/wilfred-dev/wilfred/wilfred/wilfred.py", line 107, in main
    cli()
  File "/home/vilhelm/.local/share/virtualenvs/wilfred-SNdVLYox/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/vilhelm/.local/share/virtualenvs/wilfred-SNdVLYox/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/vilhelm/.local/share/virtualenvs/wilfred-SNdVLYox/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/vilhelm/.local/share/virtualenvs/wilfred-SNdVLYox/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/vilhelm/.local/share/virtualenvs/wilfred-SNdVLYox/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/vilhelm/src/github/wilfred-dev/wilfred/wilfred/wilfred.py", line 501, in server_console
    server, disable_user_input=True if server.status == "installing" else False
  File "/home/vilhelm/src/github/wilfred-dev/wilfred/wilfred/servers.py", line 216, in console
    if not _thread._running:
UnboundLocalError: local variable '_thread' referenced before assignment
```

**Comment by VilhelmPrytz** [comment]
Will be included in the next release, `v0.5.1`.
